In [1]:
import pandas as pd

import tensorflow as tf
from tensorflow import feature_column

from sklearn.model_selection import train_test_split

import warnings 
warnings.filterwarnings('ignore')

In [ ]:
# read data if you are using Google Colab, in case of running this notebook on Jupyter, just omit this cell
from google.colab import files
uploaded = files.upload()

In [3]:
df = pd.read_csv("training.csv")

In [4]:
df.head()

       id   posted_time  ...  participant5_influence     rank
0  175339  1.514050e+12  ...                 0.23077  0.73677
1  175348  1.514110e+12  ...                 0.23077  0.78240
2  175353  1.514120e+12  ...                 0.23077  0.82125
3  175371  1.514190e+12  ...                 0.23077  0.61522
4  175372  1.514190e+12  ...                 0.23077  0.61522

[5 rows x 72 columns]

In [5]:
df.shape

(9418, 72)

In [6]:
redundant_cols =  "id, updated_time, age, updated_age, owner_id, reactivity, poster_id, poster_is_lead, participant1_is_lead, participant2_is_lead, \
participant3_is_lead, participant4_is_lead, participant5_is_lead, poster_order, participant1_order, participant2_order, \
participant3_order, participant4_order, participant5_order, participant1_id, participant2_id, participant3_id, \
participant4_id, participant5_id".split(", ")

print(redundant_cols)

df.drop(redundant_cols, axis=1, inplace=True)

df.poster_focus.replace('none', 'other', inplace=True)

['id', 'updated_time', 'age', 'updated_age', 'owner_id', 'reactivity', 'poster_id', 'poster_is_lead', 'participant1_is_lead', 'participant2_is_lead', 'participant3_is_lead', 'participant4_is_lead', 'participant5_is_lead', 'poster_order', 'participant1_order', 'participant2_order', 'participant3_order', 'participant4_order', 'participant5_order', 'participant1_id', 'participant2_id', 'participant3_id', 'participant4_id', 'participant5_id']

In [7]:
df.shape

(9418, 48)

In [8]:
_NUMERIC_COLUMNS = ['posted_time', 'owner_influence', 'poster_influence', 'participant1_influence', 'participant2_influence',
                    'participant3_influence', 'participant4_influence', 'participant5_influence']

_BINARY_COLUMNS = ["is_mentions_me", "is_mentions_connections", "is_commented_by_me", "is_commented_by_connections", 
                   "is_liked_by_me", "is_liked_by_connections", "poster_is_employee", "poster_is_in_connections",
                    "participant1_is_employee", "participant1_is_in_connections",
                    "participant2_is_employee", "participant2_is_in_connections",
                    "participant3_is_employee", "participant3_is_in_connections",
                    "participant4_is_employee", "participant4_is_in_connections",
                    "participant5_is_employee", "participant5_is_in_connections"]

_GENDER_COLUMNS = ["poster_gender", "participant1_gender", "participant2_gender", "participant3_gender", "participant4_gender", "participant5_gender"]

real = {
    colname : feature_column.numeric_column(colname) \
          for colname in _NUMERIC_COLUMNS
}

In [9]:
# indicator columns for categorical features

sparse = dict()

app_type = feature_column.categorical_column_with_vocabulary_list(
    'app_type', df.app_type.unique())
app_type_1hot = feature_column.indicator_column(app_type)
sparse["app_type"] = app_type_1hot

owner_type = feature_column.categorical_column_with_vocabulary_list(
    'owner_type', df.owner_type.unique())
owner_type_1hot = feature_column.indicator_column(owner_type)
sparse["owner_type"] = owner_type_1hot

poster_focus = feature_column.categorical_column_with_vocabulary_list(
    'poster_focus', ['engineering', 'sales', 'marketing', 'management', 'financial', 'other'])
poster_focus_1hot = feature_column.indicator_column(poster_focus)
sparse["poster_focus"] = poster_focus_1hot

for col in _GENDER_COLUMNS:
  feature = feature_column.categorical_column_with_vocabulary_list(
      col, df[col].unique())
  feature_1hot = feature_column.indicator_column(feature)
  sparse[col] = feature_1hot

# functions to reduce code duplication
def participant_action(part_action):
    participant_action = feature_column.categorical_column_with_vocabulary_list(
        part_action, ['commented', 'liked', 'viewed'])
    return participant_action

def participant_focus(part_f):
    participant_focus = feature_column.categorical_column_with_vocabulary_list(
        part_f, ['engineering', 'sales', 'marketing', 'management', 'financial', 'other', 'none'])
    return participant_focus

participant1_action = participant_action("participant1_action")
participant2_action = participant_action("participant2_action")
participant3_action = participant_action("participant3_action")
participant4_action = participant_action("participant4_action")
participant5_action = participant_action("participant5_action")

participant1_focus = participant_focus("participant1_focus")
participant2_focus = participant_focus("participant2_focus")
participant3_focus = participant_focus("participant3_focus")
participant4_focus = participant_focus("participant4_focus")
participant5_focus = participant_focus("participant5_focus")

sparse["participant1_action"] = feature_column.indicator_column(participant1_action)
sparse["participant2_action"] = feature_column.indicator_column(participant2_action)
sparse["participant3_action"] = feature_column.indicator_column(participant3_action)
sparse["participant4_action"] = feature_column.indicator_column(participant4_action)
sparse["participant5_action"] = feature_column.indicator_column(participant5_action)

sparse["participant1_focus"] = feature_column.indicator_column(participant1_focus)
sparse["participant2_focus"] = feature_column.indicator_column(participant2_focus)
sparse["participant3_focus"] = feature_column.indicator_column(participant3_focus)
sparse["participant4_focus"] = feature_column.indicator_column(participant4_focus)
sparse["participant5_focus"] = feature_column.indicator_column(participant5_focus)

In [10]:
inputs = {
    colname : tf.keras.layers.Input(name=colname, shape=(), dtype='float32') \
          for colname in real.keys()
}

inputs.update({
    colname : tf.keras.layers.Input(name=colname, shape=(), dtype='string') \
          for colname in sparse.keys()
})

In [11]:
for col in _BINARY_COLUMNS:
  feature = feature_column.categorical_column_with_vocabulary_list(
      col, df[col].unique())
  feature_1hot = feature_column.indicator_column(feature)
  sparse[col] = feature_1hot

likes_num = feature_column.numeric_column("number_of_likes")
likes_num_buckets = feature_column.bucketized_column(likes_num, boundaries=[2, 5, 10, 20, 50, 100])
sparse["number_of_likes"] = likes_num_buckets

comments_num = feature_column.numeric_column("number_of_comments")
comments_num_buckets = feature_column.bucketized_column(comments_num, boundaries=[1, 2, 5, 10, 20, 50, 100])
sparse["number_of_comments"] = comments_num_buckets


inputs.update({
    colname : tf.keras.layers.Input(name=colname, shape=(), dtype='int64') \
          for colname in _BINARY_COLUMNS + ["number_of_likes", "number_of_comments"]
})

In [12]:
opt = tf.keras.optimizers.Adam()

def wide_and_deep_classifier(inputs, linear_feature_columns, dnn_feature_columns, dnn_hidden_units):
    deep = tf.keras.layers.DenseFeatures(dnn_feature_columns)(inputs)
    for numnodes in dnn_hidden_units:
        deep = tf.keras.layers.Dense(numnodes, activation='relu')(deep)
    wide = tf.keras.layers.DenseFeatures(linear_feature_columns)(inputs)
    both = tf.keras.layers.concatenate([deep, wide])
    output = tf.keras.layers.Dense(1)(both)
    model = tf.keras.Model(inputs, output)

    model.compile(loss='mean_absolute_error',
                  optimizer= opt,
                  metrics=['mean_absolute_error'])
    return model

model = wide_and_deep_classifier(inputs, sparse.values(), real.values(), [256, 512, 256, 256, 128, 64, 32, 16])

In [13]:
def df_to_dataset(dataframe, shuffle=True, batch_size=32):
    dataframe = dataframe.copy()
    labels = dataframe.pop('rank')
    ds = tf.data.Dataset.from_tensor_slices((dict(dataframe), labels))
    if shuffle:
        ds = ds.shuffle(buffer_size=len(dataframe))
    ds = ds.batch(batch_size)
    return ds

In [14]:
train, test = train_test_split(df, test_size=0.2)
train, val = train_test_split(train, test_size=0.2)

train_ds = df_to_dataset(train)
val_ds = df_to_dataset(val, shuffle=False)
test_ds = df_to_dataset(test, shuffle=False)

In [ ]:
model.fit(train_ds,
          validation_data=val_ds,
          epochs=50)

In [16]:

results = model.evaluate(test_ds, batch_size=32)
print("Test loss: {}\nTest accuracy: {}".format(results[0], results[1]))

59/59 [==============================] - 1s 10ms/step - loss: 0.0213 - mean_absolute_error: 0.0213
Test loss: 0.021288353949785233
Test accuracy: 0.021288353949785233